### ISSUE TITLE
Upgrade NextJS (AntD combination) to latest version

### ISSUE THREAD

**Issue by webbertakken** [game-ci/documentation#223]
Currently we haven't looking into upgrading NextJS for the documentation website for a while, because the combination between latest AntD and NextJS did not seem to work.

Now, more than a year later it will probably be feasible, looking at the with-ant example from NextJS.

**Comment by kelvinsanchez15** [comment]
I'm trying to do this upgrade but right now there is no official support for Next+AntD+Less, they even deleted the integration example. 

- [Any plan to support less?](https://github.com/vercel/next.js/discussions/22823)
- [What happened to the `less` examples?](https://github.com/vercel/next.js/discussions/26284)

I think using something like [next-plugin-antd-less](https://www.npmjs.com/package/next-plugin-antd-less) could do the trick but I wanted to ask first since this is my first contribution.

**Comment by webbertakken** [comment]
Interesting. If that plugin indeed does the trick it would be great to be honest. Staying on older versions is also a bit of a pain, especially without official examples and support.

**Comment by webbertakken** [comment]
Might just move to tailwind instead when upgrading to Next12, to make this a little bit lower maintenance.

**Comment by webbertakken** [comment]
Superseded by #259
