### ISSUE TITLE
Fix `getting-started.tsx` type check

### ISSUE THREAD

**Issue by EricRibeiro** [game-ci/documentation#324]
**Bug description**

The `getting-started.tsx` file fails the type check ran by the pre-commit hook with the following message:

```
src/components/pages/home/section/getting-started.tsx:1:26 - error TS2307: Cannot find module '@site/src/components/molecules/animations/fade-into-view' or its corresponding type declarations.

1 import FadeIntoView from '@site/src/components/molecules/animations/fade-into-view';
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/components/pages/home/section/getting-started.tsx:2:18 - error TS2307: Cannot find module '@docusaurus/Link' or its corresponding type declarations.

2 import Link from '@docusaurus/Link';
                   ~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/components/pages/home/section/getting-started.tsx:1

```

**Steps to reproduce**

To reproduce it, run the following command:

```
npx tsc --skipLibCheck --noEmit --jsx react --esModuleInterop src/components/pages/home/section/getting-started.tsx
```

Alternatively, modify the file, stage it and run:

```
npx lefthook run pre-commit
```

**Expected behavior**

The type check should not fail.

**Additional details**

**Comment by timagixe** [comment]
@EricRibeiro I am willing to help with this. Please assign this issue to me. Thank you!

**Comment by EricRibeiro** [comment]
Hi, @timagixe 👋 

Will do, thank you!

**Comment by timagixe** [comment]
Hi @EricRibeiro, I had some time to take a look on this one and didn't find a resolution for this issue. I will continue to work on this one. Cheers!

**Comment by webbertakken** [comment]
Note that there are 2 different causes.

- `'@docusaurus/Link'` should resolve types from the Docusaurus project.
- `'@site/src/components/molecules/animations/fade-into-view';` is an internal component that should either be inferred (after point 1 is fixed) or we'd have to manually add types for it if that is somehow not possible.

**Comment by timagixe** [comment]
Hi @webbertakken, @EricRibeiro, I have opened PR that fixes those type errors when running type check on pre-commit step.

It appears that `tsc` fallbacks to default compiler configuration when running on specific files, i.e. `tsc ./src/index.tsx` - runs with default configuration, while `tsc` runs with configuration from `tsconfig.json`. Docs - [tsc CLI Options docs](https://www.typescriptlang.org/docs/handbook/compiler-options.html#:~:text=%23%20Emit%20JS%20for,tsc%20src/*.ts).
```
# Emit JS for just the index.ts with the compiler defaults
tsc index.ts
# Emit JS for any .ts files in the folder src, with the default settings
tsc src/*.ts
```
That's why type check on pre-commit step was failing, since configuration specified in `tsconfig.json` was ignored and instead the default one was used.

**Comment by EricRibeiro** [comment]
Thanks, @timagixe 🙇
